# Generated by Django 3.2.7 on 2021-09-26 05:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0004_auto_20210926_0531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='likes',
            field=models.ManyToManyField(related_name='like', through='board.Like', to=settings.AUTH_USER_MODEL),
        ),
    ]
