# Generated by Django 3.2.7 on 2021-09-26 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_alter_question_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_question', to='board.question'),
        ),
    ]
