FROM python:3.7

MAINTAINER ANDY

ENV PYTHONUNBUFFERED 1

# Set a Working Directory
WORKDIR /app/

# Install Production Dependecies First
COPY requirements/ /app/requirements/
RUN pip install --no-cache-dir -r requirements/requirements-dev.txt
